# Generated by Django 2.1.1 on 2019-03-13 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Left_name_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Left_name_data_lists',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_list_name', models.CharField(max_length=255)),
                ('left_name_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Left_name_data')),
            ],
        ),
        migrations.CreateModel(
            name='list_user_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Req_list_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('req', models.CharField(max_length=20)),
                ('url', models.SlugField(max_length=255)),
                ('params', models.CharField(max_length=20)),
                ('headers', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=20)),
                ('describe', models.TextField()),
                ('data_list_name', models.CharField(max_length=20)),
            ],
        ),
    ]
