# Generated by Django 2.1.1 on 2019-03-31 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0002_interface_asserts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_asserts',
            name='Req_list_data_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Req_list_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interface_asserts',
            name='left_contrast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interface_asserts',
            name='right_contrast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
