# Generated by Django 2.1.1 on 2019-03-31 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0004_auto_20190331_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_list_data',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='req_list_data',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interface_asserts',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interface_asserts',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
