# Generated by Django 2.1.1 on 2019-03-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0005_auto_20190331_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interface_asserts',
            new_name='desk_asserts',
        ),
    ]
