# Generated by Django 2.1.1 on 2019-03-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0006_auto_20190331_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='desk_asserts',
            new_name='autoin_asserts',
        ),
    ]
