# Generated by Django 2.1.1 on 2019-04-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0007_auto_20190331_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='list_user_info',
        ),
    ]
