# Generated by Django 2.1.1 on 2019-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0011_remove_req_list_data_assert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoin_asserts',
            name='right_contrast_int',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
