# Generated by Django 2.1.1 on 2019-07-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0012_autoin_asserts_right_contrast_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_list_data',
            name='way_body',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
