# Generated by Django 2.1.1 on 2019-07-23 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0013_req_list_data_way_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='req_body',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keys', models.CharField(max_length=255, null=True)),
                ('text_file', models.CharField(max_length=20, null=True)),
                ('values', models.CharField(max_length=255, null=True)),
                ('describe', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('req_body_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Req_list_data')),
            ],
        ),
    ]
