# Generated by Django 2.1.1 on 2019-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0014_req_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_list_data',
            name='body',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
