# Generated by Django 2.1.1 on 2019-03-13 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_distribution_task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_user_info_id', models.CharField(max_length=255)),
                ('req_list_data_id', models.CharField(max_length=255)),
                ('task_name_id', models.CharField(max_length=255)),
                ('work_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='work_run_task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('req_list_data_id', models.CharField(max_length=255)),
                ('run_name', models.CharField(max_length=255)),
                ('work_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('if_work', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='work_tasking_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('describe', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('req_list_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Left_name_data_lists')),
            ],
        ),
        migrations.CreateModel(
            name='work_tasking_name',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('describe', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='work_tasking_list',
            name='work_tasking_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_center.work_tasking_name'),
        ),
    ]
