# Generated by Django 2.1.1 on 2019-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0004_auto_20190331_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_asserts',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
