# Generated by Django 2.1.1 on 2019-03-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0005_interface_asserts_describe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interface_asserts',
            new_name='desk_center_asserts',
        ),
    ]
