# Generated by Django 2.1.1 on 2019-04-14 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0006_auto_20190331_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='sy_cook_vr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('csrftokens', models.CharField(max_length=255)),
                ('vrs', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
