# Generated by Django 2.1.1 on 2019-04-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0007_sy_cook_vr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sy_cook_vr',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sy_cook_vr',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
