# Generated by Django 2.1.1 on 2019-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0008_auto_20190414_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_user_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
