# Generated by Django 2.1.1 on 2019-04-03 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0010_task_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_projects',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task_projects',
            name='create_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_projects',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task_projects',
            name='update_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
