# Generated by Django 2.1.1 on 2019-05-02 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0011_auto_20190403_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_project_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_name_model', models.CharField(max_length=255)),
                ('pro_text_model', models.TextField(null=True)),
                ('create_name', models.CharField(max_length=255)),
                ('update_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
