# Generated by Django 2.1.1 on 2019-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0012_task_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_project_model',
            name='task_projects_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
