# Generated by Django 2.1.1 on 2019-06-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0015_work_distribution_task_model_work_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_historys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('execute_sign', models.CharField(max_length=200, null=True)),
                ('task_name', models.CharField(max_length=200)),
                ('task_state', models.CharField(max_length=200)),
                ('states', models.CharField(max_length=200)),
                ('execute_situation', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
