# Generated by Django 2.1.1 on 2019-06-16 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0016_work_historys'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_historys',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='work_historys',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
