# Generated by Django 2.1.1 on 2019-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0018_auto_20190616_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_historys',
            name='task_state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
