# Generated by Django 2.1.1 on 2019-07-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0021_work_historys_req_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_historys',
            name='req_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Req_list_data'),
        ),
    ]
