# Generated by Django 2.1.1 on 2019-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0023_files_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='sy_cook_vr',
            name='user_login_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
