# Generated by Django 2.1.1 on 2019-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0024_sy_cook_vr_user_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_historys',
            name='task_module',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
